import type { ClipItem, QueryFilters, VideoItem } from "./types";

const thumbnails = {
  whiteboard:
    "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80",
  interview:
    "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1200&q=80",
  webcam:
    "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
  podcast:
    "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=80",
  keynote:
    "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1200&q=80",
  failed:
    "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?auto=format&fit=crop&w=1200&q=80",
};

export const defaultFilters: QueryFilters = {
  quality: "any",
  type: "any",
  duration: "any",
  faceVisible: false,
  audioClean: false,
  hasTranscript: false,
  exportableOnly: false,
};

export const mockVideos: VideoItem[] = [
  {
    id: "video_whiteboard_lecture",
    title: "Whiteboard Lecture",
    filename: "whiteboard-lecture.mp4",
    sourceType: "example",
    status: "complete",
    thumbnailUrl: thumbnails.whiteboard,
    durationSeconds: 184,
    fileSizeMb: 118,
    resolution: "1920x1080",
    fps: 29.97,
    clipsFound: 22,
    goodClips: 14,
    reviewClips: 5,
    rejectedClips: 3,
    createdAt: "2026-05-12T17:40:00Z",
  },
  {
    id: "video_startup_interview",
    title: "Startup Interview",
    filename: "founder-interview.mov",
    sourceType: "example",
    status: "complete",
    thumbnailUrl: thumbnails.interview,
    durationSeconds: 312,
    fileSizeMb: 204,
    resolution: "1920x1080",
    fps: 30,
    clipsFound: 28,
    goodClips: 19,
    reviewClips: 6,
    rejectedClips: 3,
    createdAt: "2026-05-12T16:18:00Z",
  },
  {
    id: "video_podcast_clip",
    title: "Podcast Clip",
    filename: "podcast-studio.webm",
    sourceType: "youtube",
    status: "complete",
    thumbnailUrl: thumbnails.podcast,
    durationSeconds: 246,
    fileSizeMb: 96,
    resolution: "1280x720",
    fps: 24,
    clipsFound: 17,
    goodClips: 12,
    reviewClips: 4,
    rejectedClips: 1,
    createdAt: "2026-05-12T14:52:00Z",
  },
  {
    id: "video_noisy_webcam",
    title: "Noisy Webcam Recording",
    filename: "webcam-demo.mkv",
    sourceType: "upload",
    status: "complete",
    thumbnailUrl: thumbnails.webcam,
    durationSeconds: 142,
    fileSizeMb: 74,
    resolution: "1280x720",
    fps: 30,
    clipsFound: 13,
    goodClips: 4,
    reviewClips: 5,
    rejectedClips: 4,
    createdAt: "2026-05-12T13:21:00Z",
  },
  {
    id: "video_keynote_processing",
    title: "Conference Keynote Upload",
    filename: "keynote-upload.mp4",
    sourceType: "upload",
    status: "processing",
    progressStage: "running_face_detection",
    progressPercent: 62,
    thumbnailUrl: thumbnails.keynote,
    durationSeconds: 278,
    fileSizeMb: 188,
    resolution: "1920x1080",
    fps: 29.97,
    clipsFound: 12,
    goodClips: 0,
    reviewClips: 0,
    rejectedClips: 0,
    createdAt: "2026-05-12T18:05:00Z",
  },
  {
    id: "video_failed_screen_recording",
    title: "Corrupted Screen Recording",
    filename: "broken-screen-recording.mp4",
    sourceType: "upload",
    status: "failed",
    thumbnailUrl: thumbnails.failed,
    durationSeconds: 97,
    fileSizeMb: 41,
    clipsFound: 0,
    goodClips: 0,
    reviewClips: 0,
    rejectedClips: 0,
    createdAt: "2026-05-12T12:44:00Z",
    error: "Decode failed before speech detection. Try re-exporting the file.",
  },
];

export const mockClips: ClipItem[] = [
  {
    id: "clip_whiteboard_001",
    videoId: "video_whiteboard_lecture",
    sourceVideoTitle: "Whiteboard Lecture",
    clipUrl: "/mock/clips/whiteboard-001.mp4",
    thumbnailUrl: thumbnails.whiteboard,
    startTime: 12.4,
    endTime: 22.8,
    duration: 10.4,
    quality: "good",
    qualityScore: 0.91,
    speechScore: 0.91,
    faceScore: 0.87,
    audioScore: 0.82,
    transcript: "Today I want to explain how this model works from the whiteboard up.",
    tags: ["human-speaking", "face-visible", "clean-audio", "whiteboard", "single-speaker"],
    exportable: true,
  },
  {
    id: "clip_whiteboard_002",
    videoId: "video_whiteboard_lecture",
    sourceVideoTitle: "Whiteboard Lecture",
    clipUrl: "/mock/clips/whiteboard-002.mp4",
    thumbnailUrl: thumbnails.whiteboard,
    startTime: 37.1,
    endTime: 51.9,
    duration: 14.8,
    quality: "good",
    qualityScore: 0.88,
    speechScore: 0.9,
    faceScore: 0.78,
    audioScore: 0.84,
    transcript: "The important part is the transition from raw frames to searchable metadata.",
    tags: ["human-speaking", "face-visible", "clean-audio", "whiteboard"],
    exportable: true,
  },
  {
    id: "clip_whiteboard_003",
    videoId: "video_whiteboard_lecture",
    sourceVideoTitle: "Whiteboard Lecture",
    clipUrl: "/mock/clips/whiteboard-003.mp4",
    thumbnailUrl: thumbnails.whiteboard,
    startTime: 66.5,
    endTime: 74.4,
    duration: 7.9,
    quality: "review",
    qualityScore: 0.64,
    speechScore: 0.73,
    faceScore: 0.52,
    audioScore: 0.8,
    transcript: "This example is a little hard to see, but the labels still line up.",
    tags: ["human-speaking", "whiteboard", "needs-review"],
    exportable: true,
  },
  {
    id: "clip_whiteboard_004",
    videoId: "video_whiteboard_lecture",
    sourceVideoTitle: "Whiteboard Lecture",
    clipUrl: "/mock/clips/whiteboard-004.mp4",
    thumbnailUrl: thumbnails.whiteboard,
    startTime: 104.2,
    endTime: 112.1,
    duration: 7.9,
    quality: "rejected",
    qualityScore: 0.22,
    speechScore: 0.31,
    faceScore: 0.18,
    audioScore: 0.44,
    transcript: "A long pause while the camera points away from the speaker.",
    tags: ["whiteboard", "bad-framing"],
    rejectionReasons: ["no face detected", "too much silence"],
    exportable: false,
  },
  {
    id: "clip_startup_001",
    videoId: "video_startup_interview",
    sourceVideoTitle: "Startup Interview",
    clipUrl: "/mock/clips/startup-001.mp4",
    thumbnailUrl: thumbnails.interview,
    startTime: 8.2,
    endTime: 26.6,
    duration: 18.4,
    quality: "good",
    qualityScore: 0.94,
    speechScore: 0.96,
    faceScore: 0.9,
    audioScore: 0.89,
    transcript: "We started by curating the examples that made the model fail in production.",
    tags: ["human-speaking", "face-visible", "clean-audio", "startup-pitch", "single-speaker"],
    exportable: true,
  },
  {
    id: "clip_startup_002",
    videoId: "video_startup_interview",
    sourceVideoTitle: "Startup Interview",
    clipUrl: "/mock/clips/startup-002.mp4",
    thumbnailUrl: thumbnails.interview,
    startTime: 42.5,
    endTime: 61.3,
    duration: 18.8,
    quality: "good",
    qualityScore: 0.89,
    speechScore: 0.93,
    faceScore: 0.82,
    audioScore: 0.86,
    transcript: "The search layer lets reviewers find clips by transcript, concept, and quality.",
    tags: ["human-speaking", "face-visible", "clean-audio", "office-interview"],
    exportable: true,
  },
  {
    id: "clip_startup_003",
    videoId: "video_startup_interview",
    sourceVideoTitle: "Startup Interview",
    clipUrl: "/mock/clips/startup-003.mp4",
    thumbnailUrl: thumbnails.interview,
    startTime: 88.3,
    endTime: 112.9,
    duration: 24.6,
    quality: "review",
    qualityScore: 0.68,
    speechScore: 0.81,
    faceScore: 0.76,
    audioScore: 0.58,
    transcript: "There is some room noise here, but the answer is useful for training data.",
    tags: ["human-speaking", "face-visible", "startup-pitch", "background-noise"],
    exportable: true,
  },
  {
    id: "clip_startup_004",
    videoId: "video_startup_interview",
    sourceVideoTitle: "Startup Interview",
    clipUrl: "/mock/clips/startup-004.mp4",
    thumbnailUrl: thumbnails.interview,
    startTime: 140.1,
    endTime: 149.6,
    duration: 9.5,
    quality: "rejected",
    qualityScore: 0.28,
    speechScore: 0.44,
    faceScore: 0.41,
    audioScore: 0.33,
    transcript: "The interviewer talks over the speaker during this section.",
    tags: ["overlap", "background-noise"],
    rejectionReasons: ["overlapping speech", "audio clipping"],
    exportable: false,
  },
  {
    id: "clip_podcast_001",
    videoId: "video_podcast_clip",
    sourceVideoTitle: "Podcast Clip",
    clipUrl: "/mock/clips/podcast-001.mp4",
    thumbnailUrl: thumbnails.podcast,
    startTime: 18.4,
    endTime: 39.1,
    duration: 20.7,
    quality: "good",
    qualityScore: 0.86,
    speechScore: 0.92,
    faceScore: 0.75,
    audioScore: 0.91,
    transcript: "The dataset should include enough variation to cover real speaking conditions.",
    tags: ["human-speaking", "face-visible", "clean-audio", "podcast", "single-speaker"],
    exportable: true,
  },
  {
    id: "clip_podcast_002",
    videoId: "video_podcast_clip",
    sourceVideoTitle: "Podcast Clip",
    clipUrl: "/mock/clips/podcast-002.mp4",
    thumbnailUrl: thumbnails.podcast,
    startTime: 58.9,
    endTime: 69.2,
    duration: 10.3,
    quality: "good",
    qualityScore: 0.83,
    speechScore: 0.88,
    faceScore: 0.7,
    audioScore: 0.9,
    transcript: "Clean audio matters more than perfect lighting for this downstream task.",
    tags: ["human-speaking", "face-visible", "clean-audio", "podcast"],
    exportable: true,
  },
  {
    id: "clip_podcast_003",
    videoId: "video_podcast_clip",
    sourceVideoTitle: "Podcast Clip",
    clipUrl: "/mock/clips/podcast-003.mp4",
    thumbnailUrl: thumbnails.podcast,
    startTime: 120.3,
    endTime: 129.6,
    duration: 9.3,
    quality: "review",
    qualityScore: 0.61,
    speechScore: 0.72,
    faceScore: 0.48,
    audioScore: 0.87,
    transcript: "The face is partially blocked by the microphone arm.",
    tags: ["human-speaking", "clean-audio", "occluded-face"],
    exportable: true,
  },
  {
    id: "clip_webcam_001",
    videoId: "video_noisy_webcam",
    sourceVideoTitle: "Noisy Webcam Recording",
    clipUrl: "/mock/clips/webcam-001.mp4",
    thumbnailUrl: thumbnails.webcam,
    startTime: 5.6,
    endTime: 13.8,
    duration: 8.2,
    quality: "good",
    qualityScore: 0.77,
    speechScore: 0.84,
    faceScore: 0.8,
    audioScore: 0.72,
    transcript: "I am going to walk through the setup quickly before the demo starts.",
    tags: ["human-speaking", "face-visible", "single-speaker"],
    exportable: true,
  },
  {
    id: "clip_webcam_002",
    videoId: "video_noisy_webcam",
    sourceVideoTitle: "Noisy Webcam Recording",
    clipUrl: "/mock/clips/webcam-002.mp4",
    thumbnailUrl: thumbnails.webcam,
    startTime: 22.4,
    endTime: 38.7,
    duration: 16.3,
    quality: "review",
    qualityScore: 0.57,
    speechScore: 0.66,
    faceScore: 0.82,
    audioScore: 0.42,
    transcript: "The screen share is visible, but the fan noise is strong in the background.",
    tags: ["human-speaking", "face-visible", "bad-audio", "screen-share"],
    exportable: true,
  },
  {
    id: "clip_webcam_003",
    videoId: "video_noisy_webcam",
    sourceVideoTitle: "Noisy Webcam Recording",
    clipUrl: "/mock/clips/webcam-003.mp4",
    thumbnailUrl: thumbnails.webcam,
    startTime: 71.2,
    endTime: 86.4,
    duration: 15.2,
    quality: "rejected",
    qualityScore: 0.19,
    speechScore: 0.22,
    faceScore: 0.79,
    audioScore: 0.21,
    transcript: "The speaker is visible, but the audio is mostly static.",
    tags: ["face-visible", "bad-audio", "static"],
    rejectionReasons: ["speech confidence too low", "audio too noisy"],
    exportable: false,
  },
  {
    id: "clip_webcam_004",
    videoId: "video_noisy_webcam",
    sourceVideoTitle: "Noisy Webcam Recording",
    clipUrl: "/mock/clips/webcam-004.mp4",
    thumbnailUrl: thumbnails.webcam,
    startTime: 100.5,
    endTime: 122.6,
    duration: 22.1,
    quality: "good",
    qualityScore: 0.8,
    speechScore: 0.86,
    faceScore: 0.83,
    audioScore: 0.76,
    transcript: "Once the microphone is closer, the same webcam source becomes usable.",
    tags: ["human-speaking", "face-visible", "single-speaker"],
    exportable: true,
  },
];
